"""Domain-randomization profiles for Robotis OMX Isaac Lab Mimic runs."""

from __future__ import annotations


DOMAIN_RANDOMIZATION_PROFILES: dict[str, dict[str, tuple[float, float]]] = {
    "off": {
        "cube_xy_m": (0.0, 0.0),
        "cube_yaw_rad": (0.0, 0.0),
        "cube_mass_scale": (1.0, 1.0),
        "cube_static_friction": (0.9, 0.9),
        "cube_dynamic_friction": (0.7, 0.7),
        "gripper_inner_static_friction": (1.2, 1.2),
        "camera_pose_xyz_m": (0.0, 0.0),
        "lighting_intensity_scale": (1.0, 1.0),
        "color_temperature_shift_k": (0.0, 0.0),
        "shadow_softness_scale": (1.0, 1.0),
        "table_color_brightness": (1.0, 1.0),
        "background_brightness": (1.0, 1.0),
        "a4_brightness": (1.0, 1.0),
        "camera_exposure_scale": (1.0, 1.0),
        "camera_gamma": (1.0, 1.0),
        "white_balance_rgb_scale": (1.0, 1.0),
        "rgb_noise_sigma": (0.0, 0.0),
        "rgb_blur_px": (0.0, 0.0),
        "depth_noise_mm": (0.0, 0.0),
        "depth_dropout_ratio": (0.0, 0.0),
    },
    "conservative": {
        "cube_xy_m": (0.0, 0.0),
        "cube_yaw_rad": (0.0, 0.0),
        "cube_mass_scale": (1.0, 1.0),
        "cube_static_friction": (0.9, 0.9),
        "cube_dynamic_friction": (0.7, 0.7),
        "gripper_inner_static_friction": (1.2, 1.2),
        "camera_pose_xyz_m": (0.0, 0.0),
        "lighting_intensity_scale": (0.9, 1.1),
        "color_temperature_shift_k": (-200.0, 200.0),
        "shadow_softness_scale": (0.9, 1.1),
        "table_color_brightness": (0.92, 1.08),
        "background_brightness": (0.92, 1.1),
        "a4_brightness": (0.96, 1.04),
        "camera_exposure_scale": (0.95, 1.05),
        "camera_gamma": (0.98, 1.02),
        "white_balance_rgb_scale": (0.98, 1.02),
        "rgb_noise_sigma": (0.0, 0.006),
        "rgb_blur_px": (0.0, 0.25),
        "depth_noise_mm": (0.0, 0.8),
        "depth_dropout_ratio": (0.0, 0.004),
    },
    "standard": {
        "cube_xy_m": (0.0, 0.0),
        "cube_yaw_rad": (0.0, 0.0),
        "cube_mass_scale": (1.0, 1.0),
        "cube_static_friction": (0.9, 0.9),
        "cube_dynamic_friction": (0.7, 0.7),
        "gripper_inner_static_friction": (1.2, 1.2),
        "camera_pose_xyz_m": (0.0, 0.0),
        "lighting_intensity_scale": (0.75, 1.25),
        "color_temperature_shift_k": (-400.0, 400.0),
        "shadow_softness_scale": (0.85, 1.2),
        "table_color_brightness": (0.85, 1.15),
        "background_brightness": (0.85, 1.2),
        "a4_brightness": (0.92, 1.08),
        "camera_exposure_scale": (0.9, 1.1),
        "camera_gamma": (0.95, 1.05),
        "white_balance_rgb_scale": (0.96, 1.04),
        "rgb_noise_sigma": (0.0, 0.012),
        "rgb_blur_px": (0.0, 0.5),
        "depth_noise_mm": (0.0, 1.5),
        "depth_dropout_ratio": (0.0, 0.008),
    },
    "mimic_pose": {
        "cube_xy_m": (-0.015, 0.015),
        "cube_yaw_rad": (-0.12, 0.12),
        "cube_mass_scale": (1.0, 1.0),
        "cube_static_friction": (0.9, 0.9),
        "cube_dynamic_friction": (0.7, 0.7),
        "gripper_inner_static_friction": (1.2, 1.2),
        "camera_pose_xyz_m": (0.0, 0.0),
        "lighting_intensity_scale": (0.9, 1.1),
        "color_temperature_shift_k": (-200.0, 200.0),
        "shadow_softness_scale": (0.9, 1.1),
        "table_color_brightness": (0.92, 1.08),
        "background_brightness": (0.92, 1.1),
        "a4_brightness": (0.96, 1.04),
        "camera_exposure_scale": (0.95, 1.05),
        "camera_gamma": (0.98, 1.02),
        "white_balance_rgb_scale": (0.98, 1.02),
        "rgb_noise_sigma": (0.0, 0.006),
        "rgb_blur_px": (0.0, 0.25),
        "depth_noise_mm": (0.0, 0.8),
        "depth_dropout_ratio": (0.0, 0.004),
    },
    "stress": {
        "cube_xy_m": (0.0, 0.0),
        "cube_yaw_rad": (0.0, 0.0),
        "cube_mass_scale": (1.0, 1.0),
        "cube_static_friction": (0.9, 0.9),
        "cube_dynamic_friction": (0.7, 0.7),
        "gripper_inner_static_friction": (1.2, 1.2),
        "camera_pose_xyz_m": (0.0, 0.0),
        "lighting_intensity_scale": (0.6, 1.4),
        "color_temperature_shift_k": (-700.0, 700.0),
        "shadow_softness_scale": (0.7, 1.35),
        "table_color_brightness": (0.75, 1.25),
        "background_brightness": (0.75, 1.3),
        "a4_brightness": (0.88, 1.12),
        "camera_exposure_scale": (0.85, 1.15),
        "camera_gamma": (0.92, 1.08),
        "white_balance_rgb_scale": (0.94, 1.06),
        "rgb_noise_sigma": (0.0, 0.02),
        "rgb_blur_px": (0.0, 0.75),
        "depth_noise_mm": (0.0, 2.5),
        "depth_dropout_ratio": (0.0, 0.015),
    },
}


def get_profile(name: str) -> dict[str, tuple[float, float]]:
    return DOMAIN_RANDOMIZATION_PROFILES.get(name, DOMAIN_RANDOMIZATION_PROFILES["conservative"])


def event_ranges(name: str) -> dict[str, tuple[float, float]]:
    profile = get_profile(name)
    return {
        "cube_static_friction_range": profile["cube_static_friction"],
        "cube_dynamic_friction_range": profile["cube_dynamic_friction"],
        "cube_mass_scale_range": profile["cube_mass_scale"],
        "cube_rest_offset_range": (0.0, 0.0),
        "cube_contact_offset_range": (0.004, 0.004),
    }
