"""Unit tests for deterministic Bambu G-code autoejection artifact patching."""

from __future__ import annotations

import hashlib
import json
import zipfile
from pathlib import Path

import pytest

from device_bridges.bambu_autoejection import (
    BambuGcodeAutoejectionPatcher,
    BambuGcodeAutoejectionValidator,
    extract_object_bounds_mm,
)


BASE_GCODE = """; generated by Bambu Studio
; filament start gcode
G90
G1 X10.0 Y20.0 Z0.2 E0.03 F1200
G1 X40.0 Y55.0 Z10.0 E2.50 F1800
M104 S0
M140 S0
M84
"""


def test_plain_gcode_patch_inserts_single_validated_bambu_ejection_tail(tmp_path: Path) -> None:
    source = tmp_path / "specimen.gcode"
    source.write_text(BASE_GCODE, encoding="utf-8")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center")

    patched_path = Path(result["patched_artifact_path"])
    patched_text = patched_path.read_text(encoding="utf-8")
    assert result["ok"] is True
    assert result["source_plate_path"] == "plain_gcode"
    assert patched_path.name == "specimen.autoeject.gcode"
    assert patched_text.count("atr.bambu.autoejection.v1") == 1
    assert "; atr_source_sha256=" in patched_text
    assert "M190 R40" in patched_text
    assert patched_text.index("atr.bambu.autoejection.v1") < patched_text.rindex("M84")
    assert result["validation"]["ok"] is True
    assert result["object_bounds_mm"]["min_x"] == 10.0
    assert result["object_bounds_mm"]["max_y"] == 55.0
    assert result["patched_sha256"] == hashlib.sha256(patched_path.read_bytes()).hexdigest()


def test_plain_gcode_patch_inserts_tail_after_last_extrusion_when_startup_disables_motors(tmp_path: Path) -> None:
    source = tmp_path / "startup_m84.gcode"
    source.write_text(
        "\n".join(
            [
                "G90",
                "M82",
                "M84 ; startup motor reset must not be the insertion anchor",
                "G92 E0",
                "G1 X30 Y40 Z0.2 E0.1 F1200",
                "G1 X70 Y80 Z30.0 E0.4 F1200",
                "M104 S0",
                "M84 ; final motor disable",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="startup-m84", position="center")

    patched_text = Path(result["patched_artifact_path"]).read_text(encoding="utf-8")
    assert result["ok"] is True
    assert patched_text.index("G1 X70 Y80 Z30.0 E0.4") < patched_text.index("atr.bambu.autoejection.v1")
    assert patched_text.index("atr.bambu.autoejection.end") < patched_text.rindex("M84")


def test_plain_gcode_validate_only_does_not_write_patched_artifact(tmp_path: Path) -> None:
    source = tmp_path / "specimen.gcode"
    source.write_text(BASE_GCODE, encoding="utf-8")
    output_dir = tmp_path / "patched"
    patcher = BambuGcodeAutoejectionPatcher(output_dir=output_dir)

    result = patcher.validate_artifact(source, specimen_id="specimen-cand-1", position="center")

    assert result["ok"] is True
    assert result["tool"] == "printer.bambu.autoejection_validate"
    assert result["status"] == "validated"
    assert result["source_plate_path"] == "plain_gcode"
    assert result["validation"]["ok"] is True
    assert result["will_publish"] is False
    assert result["start_enabled"] is False
    assert result["patched_artifact_path"] == ""
    assert result["manifest_path"] == ""
    assert not output_dir.exists()


def test_plain_gcode_patch_records_required_runtime_tail_metadata(tmp_path: Path) -> None:
    source = tmp_path / "specimen.gcode"
    source.write_text(BASE_GCODE, encoding="utf-8")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center")

    patched_text = Path(result["patched_artifact_path"]).read_text(encoding="utf-8")
    assert result["ok"] is True
    assert "; atr_source_plate_path=plain_gcode" in patched_text
    assert "; atr_object_height_mm=10.000" in patched_text
    assert "; atr_material_type=unknown" in patched_text
    assert "; atr_bed_surface=unknown" in patched_text
    assert "; atr_bed_cooldown_c=40" in patched_text
    assert "; atr_cooldown_wait_policy=M190" in patched_text
    assert "; atr_purge_parking_strategy=preserve_slicer_end_gcode_then_eject" in patched_text
    assert "; atr_door_or_front_path_assumption=operator_confirmed_before_publish" in patched_text
    assert "; atr_toolhead_cover_risk_note=operator_confirms_cover_secured_before_publish" in patched_text
    assert "; atr_validation_result=stored_in_manifest" in patched_text
    assert "; atr_patched_artifact_sha256=stored_in_manifest" in patched_text


def test_plain_gcode_patch_pushes_at_object_center_after_bed_cooldown(tmp_path: Path) -> None:
    source = tmp_path / "specimen.gcode"
    source.write_text(
        "\n".join(
            [
                "G90",
                "M82",
                "G1 X30 Y40 Z0.2 E0.02 F1200",
                "G1 X70 Y90 Z12.0 E1.20 F1800",
                "G0 X240 Y240 F9000 ; non-extrusion travel must not move ejection center",
                "M84",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center")

    patched_text = Path(result["patched_artifact_path"]).read_text(encoding="utf-8")
    assert result["ok"] is True
    assert result["object_bounds_mm"]["min_x"] == 30.0
    assert result["object_bounds_mm"]["max_x"] == 70.0
    assert result["object_bounds_mm"]["center_x_mm"] == 50.0
    assert result["object_bounds_mm"]["center_y_mm"] == 65.0
    assert "; atr_object_center_mm=[50.0, 65.0, 6.1]" in patched_text
    assert patched_text.index("M190 R40") < patched_text.index("G0 X50.000")
    assert "G0 Z10.000 F3000" in patched_text
    assert "G28 ; atr_autoejection_home_all_axes" not in patched_text
    assert "G1 Z5.000 F5000 ; atr_autoejection_lift_after_home" not in patched_text
    assert "; atr_home_initialization=preserve_print_job_coordinates" in patched_text
    assert "G90" in patched_text
    assert patched_text.index("G0 Z20.000 F3000") < patched_text.index("G0 X50.000 Y245.000")
    assert patched_text.index("G0 X50.000 Y245.000") < patched_text.index("G0 Z10.000 F3000")
    assert "G0 Z2.000 F3000" not in patched_text
    assert "G0 X50.000 Y245.000 F6000" in patched_text
    assert "atr_sweep_height_fraction=0.90" not in patched_text


def test_plain_gcode_patch_approaches_object_lane_above_object_before_lowering_to_push_height(tmp_path: Path) -> None:
    source = tmp_path / "collision_safe_approach.gcode"
    source.write_text(
        "\n".join(
            [
                "G90",
                "M82",
                "G92 E0",
                "G1 X30 Y40 Z0.2 E0.1 F1200",
                "G1 X70 Y80 Z40.0 E0.4 F1200",
                "M84",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched", safe_z_mm=20.0)

    result = patcher.patch_artifact(source, specimen_id="collision-safe", position="center")

    patched_text = Path(result["patched_artifact_path"]).read_text(encoding="utf-8")
    safe_z = patched_text.index("G0 Z42.000 F3000")
    approach_xy = patched_text.index("G0 X50.000 Y245.000 F6000")
    push_z = patched_text.index("G0 Z25.000 F3000")
    assert result["ok"] is True
    assert "; atr_safe_approach_z_mm=42.000" in patched_text
    assert safe_z < approach_xy < push_z


def test_bambu_bounds_parser_accepts_leading_dot_relative_extrusion() -> None:
    gcode = "\n".join(
        [
            "G90",
            "M83 ; use relative distances for extrusion",
            "G1 X82.731 Y87.536 F7200",
            "G1 Z.4",
            "G1 X117.269 Y112.464 E.02821",
            "G1 X100.000 Y120.000 Z12.0 E.5",
        ]
    )

    bounds = extract_object_bounds_mm(gcode)

    assert bounds["source"] == "extrusion_moves"
    assert bounds["extrusion_move_count"] == 2
    assert bounds["min_x"] == 82.731
    assert bounds["max_x"] == 117.269
    assert bounds["max_z"] == 12.0


def test_standalone_bambu_autoejection_builds_virtual_object_bounds_for_motion(tmp_path: Path) -> None:
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.build_standalone_ejection_artifact(
        specimen_id="standalone-right",
        position="right",
        object_size_mm=[30.0, 30.0, 12.0],
    )

    patched_text = Path(result["patched_artifact_path"]).read_text(encoding="utf-8")
    bounds = result["object_bounds_mm"]
    assert result["ok"] is True
    assert bounds["center_x_mm"] == 208.0
    assert bounds["center_y_mm"] == 126.5
    assert bounds["max_z"] == 12.0
    assert "G0 Z10.000 F3000" in patched_text
    assert "G28 ; atr_autoejection_home_all_axes" not in patched_text
    assert "G1 Z5.000 F5000 ; atr_autoejection_lift_after_home" not in patched_text
    assert "; atr_home_initialization=preserve_print_job_coordinates" in patched_text
    assert patched_text.index("G0 Z20.000 F3000") < patched_text.index("G0 X208.000 Y245.000")
    assert patched_text.index("G0 X208.000 Y245.000") < patched_text.index("G0 Z10.000 F3000")
    assert "G0 Z2.000 F3000" not in patched_text
    assert "G0 X208.000 Y245.000 F6000" in patched_text
    assert patched_text.index("M190 R40") < patched_text.index("G0 X208.000")


def test_standalone_bambu_autoejection_uses_absolute_push_height_from_object_top(tmp_path: Path) -> None:
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.build_standalone_ejection_artifact(
        specimen_id="standalone-tall",
        position="center",
        object_size_mm=[30.0, 30.0, 40.0],
    )

    patched_text = Path(result["patched_artifact_path"]).read_text(encoding="utf-8")
    assert result["ok"] is True
    assert result["object_bounds_mm"]["max_z"] == 40.0
    assert "G0 Z25.000 F3000" in patched_text
    assert patched_text.index("G0 Z42.000 F3000") < patched_text.index("G0 X128.000 Y245.000")
    assert patched_text.index("G0 X128.000 Y245.000") < patched_text.index("G0 Z25.000 F3000")
    assert "G0 Z50.000 F3000" not in patched_text


def test_plain_gcode_patch_is_idempotent_for_already_autoeject_artifact(tmp_path: Path) -> None:
    source = tmp_path / "specimen.gcode"
    source.write_text(BASE_GCODE, encoding="utf-8")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")
    first = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center")

    second = patcher.patch_artifact(first["patched_artifact_path"], specimen_id="specimen-cand-1", position="center")

    patched_path = Path(second["patched_artifact_path"])
    patched_text = patched_path.read_text(encoding="utf-8")
    assert second["ok"] is True
    assert patched_path == Path(first["patched_artifact_path"])
    assert patched_path.name == "specimen.autoeject.gcode"
    assert "autoeject.autoeject" not in patched_path.name
    assert patched_text.count("atr.bambu.autoejection.v1") == 1
    assert Path(second["manifest_path"]).name == "specimen.autoeject.gcode.manifest.json"


def test_plain_gcode_patch_keeps_bambu_end_homing_before_autoejection_tail(tmp_path: Path) -> None:
    source = tmp_path / "bambu_end_sequence.gcode"
    source.write_text(
        """; generated by Bambu Studio
G90
G1 X82.0 Y82.0 Z0.2 E0.03 F1200
G1 X118.0 Y118.0 Z30.0 E2.50 F1800
M106 S0
; FEATURE: Custom
; MACHINE_END_GCODE_START
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
M73 P100 R0
; EXECUTABLE_BLOCK_END
""",
        encoding="utf-8",
    )
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center")

    patched_text = Path(result["patched_artifact_path"]).read_text(encoding="utf-8")
    assert result["ok"] is True
    assert patched_text.index("G28 X0") < patched_text.index("atr.bambu.autoejection.v1")
    assert patched_text.index("atr.bambu.autoejection.end") < patched_text.index("M84")
    assert "BAMBU_AUTOEJECTION_UNEXPECTED_HOME" not in result["validation"]["blockers"]


def test_gcode_3mf_patch_replaces_plate_gcode_and_updates_md5(tmp_path: Path) -> None:
    source = tmp_path / "plate.gcode.3mf"
    original_md5 = hashlib.md5(BASE_GCODE.encode("utf-8")).hexdigest()
    with zipfile.ZipFile(source, "w") as archive:
        archive.writestr("Metadata/plate_1.gcode", BASE_GCODE)
        archive.writestr("Metadata/plate_1.gcode.md5", original_md5)
        archive.writestr("3D/3dmodel.model", "<model />")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="left", plate_id=1)

    patched_path = Path(result["patched_artifact_path"])
    assert result["ok"] is True
    assert patched_path.name == "plate.autoeject.gcode.3mf"
    assert result["source_plate_path"] == "Metadata/plate_1.gcode"
    with zipfile.ZipFile(patched_path) as archive:
        patched_gcode = archive.read("Metadata/plate_1.gcode").decode("utf-8")
        patched_md5 = archive.read("Metadata/plate_1.gcode.md5").decode("utf-8").strip()
        assert archive.read("3D/3dmodel.model").decode("utf-8") == "<model />"
    assert patched_gcode.count("atr.bambu.autoejection.v1") == 1
    assert patched_md5 == hashlib.md5(patched_gcode.encode("utf-8")).hexdigest()
    assert result["post_write_validation"]["ok"] is True
    assert result["post_write_validation"]["md5_matches"] is True
    assert result["validation"]["ok"] is True


def test_gcode_3mf_patch_reopens_written_artifact_and_verifies_tail_md5_and_plate(tmp_path: Path) -> None:
    source = tmp_path / "plate.gcode.3mf"
    with zipfile.ZipFile(source, "w") as archive:
        archive.writestr("Metadata/plate_1.gcode", BASE_GCODE)
        archive.writestr("3D/3dmodel.model", "<model />")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center", plate_id=1)

    post_write = result["post_write_validation"]
    assert result["ok"] is True
    assert post_write["ok"] is True
    assert post_write["reopened"] is True
    assert post_write["plate_path_matches"] is True
    assert post_write["tail_validation"]["ok"] is True
    assert post_write["md5_matches"] is True
    assert post_write["artifact_sha256"] == result["patched_sha256"]


def test_gcode_3mf_ejection_only_patch_uses_source_bounds_without_print_body(tmp_path: Path) -> None:
    source = tmp_path / "actual_specimen.gcode.3mf"
    original_gcode = "\n".join(
        [
            "; HEADER_BLOCK_START",
            "; BambuStudio test slice",
            "; estimated printing time (normal mode) = 2h 16m 39s",
            "; total layer number: 151",
            "; total filament length [mm] : 3575.51",
            "; HEADER_BLOCK_END",
            "; EXECUTABLE_BLOCK_START",
            "M73 P0 R1",
            "M201 X1000 Y1000 Z500 E5000",
            "M106 S0",
            "M190 S35 ; original print bed wait must not be needed for ejection-only validation",
            "M104 S200 ; original print nozzle heat must not be needed for ejection-only validation",
            "; FEATURE: Custom",
            "G28 ; home all axes",
            "G1 Z5 F5000 ; lift nozzle",
            "; MACHINE_START_GCODE_END",
            "M109 S200 ; original print nozzle wait must not be needed for ejection-only validation",
            "G90",
            "G21",
            "M83 ; use relative distances for extrusion",
            "; FEATURE: Outer wall",
            "G1 X30 Y40 Z0.2 E0.1 F1200",
            "G1 X70 Y40 Z0.2 E0.2 F1200",
            "G1 X70 Y80 Z12.0 E0.3 F1200",
            "G1 X30 Y80 Z12.0 E0.4 F1200",
            "; MACHINE_END_GCODE_START",
            "M104 S0 ; turn off temperature",
            "G28 X0  ; home X axis",
            "M84     ; disable motors",
            "M73 P100 R0",
            "; EXECUTABLE_BLOCK_END",
        ]
    )
    with zipfile.ZipFile(source, "w") as archive:
        archive.writestr("Metadata/plate_1.gcode", original_gcode)
        archive.writestr(
            "Metadata/slice_info.config",
            '<?xml version="1.0" encoding="UTF-8"?><config><plate><metadata key="prediction" value="8199"/></plate></config>',
        )
        archive.writestr("3D/3dmodel.model", "<model />")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.build_ejection_only_from_sliced_artifact(
        source,
        specimen_id="actual-specimen-test",
        position="center",
        plate_id=1,
        loop_index=2,
    )

    patched_path = Path(result["patched_artifact_path"])
    assert result["ok"] is True
    assert patched_path.name == "actual_specimen.ejection-test.gcode.3mf"
    assert result["object_bounds_mm"]["source"] == "extrusion_moves"
    assert result["object_bounds_mm"]["center_x_mm"] == 50.0
    assert result["object_bounds_mm"]["center_y_mm"] == 60.0
    assert result["object_bounds_mm"]["max_z"] == 12.0
    with zipfile.ZipFile(patched_path) as archive:
        patched_gcode = archive.read("Metadata/plate_1.gcode").decode("utf-8")
        patched_md5 = archive.read("Metadata/plate_1.gcode.md5").decode("utf-8").strip()
        slice_info = archive.read("Metadata/slice_info.config").decode("utf-8")
    assert patched_md5 == hashlib.md5(patched_gcode.encode("utf-8")).hexdigest()
    assert result["post_write_validation"]["ok"] is True
    assert result["post_write_validation"]["md5_matches"] is True
    assert "G28 ; home all axes" in patched_gcode
    assert "G28 X0" not in patched_gcode
    assert "M190 S35" not in patched_gcode
    assert "M104 S200" not in patched_gcode
    assert "M109 S200" not in patched_gcode
    assert "M73 P0 R1" not in patched_gcode
    assert "M73 P100 R0" in patched_gcode
    assert "2h 16m 39s" not in patched_gcode
    assert "; total layer number: 151" not in patched_gcode
    assert "; estimated printing time (normal mode) = 2m 0s" in patched_gcode
    assert "; total layer number: 1" in patched_gcode
    assert "; total filament length [mm] : 0.00" in patched_gcode
    assert 'key="prediction" value="120"' in slice_info
    assert 'value="8199"' not in slice_info
    assert "E0.1" not in patched_gcode
    assert "E0.4" not in patched_gcode
    assert "; FEATURE: Outer wall" not in patched_gcode
    assert "; atr_print_body_omitted=true" in patched_gcode
    assert "; atr_actual_object_bounds_mm=" in patched_gcode
    assert "; atr_cooldown_wait_policy=not_required_no_print_body" in patched_gcode
    assert "M190 R40" not in patched_gcode
    assert "G0 Z10.000 F3000" in patched_gcode
    assert "G0 X50.000 Y245.000 F6000" in patched_gcode
    tail = patched_gcode[patched_gcode.index("atr.bambu.autoejection.v1") :]
    assert "G28" not in tail
    assert tail.index("atr.bambu.autoejection.end") < tail.index("M73 P100 R0")

    retained = patcher.build_ejection_only_from_sliced_artifact(
        source,
        specimen_id="actual-specimen-with-cooling",
        position="center",
        plate_id=1,
        loop_index=3,
        include_cooldown_wait=True,
    )
    with zipfile.ZipFile(retained["patched_artifact_path"]) as archive:
        retained_gcode = archive.read("Metadata/plate_1.gcode").decode("utf-8")
    assert "; atr_cooldown_wait_policy=M190" in retained_gcode
    assert "M190 R40" in retained_gcode


def test_gcode_3mf_patch_blocks_missing_requested_plate_instead_of_falling_back(tmp_path: Path) -> None:
    source = tmp_path / "wrong_plate_only.gcode.3mf"
    with zipfile.ZipFile(source, "w") as archive:
        archive.writestr("Metadata/plate_2.gcode", BASE_GCODE)
        archive.writestr("3D/3dmodel.model", "<model />")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center", plate_id=1)

    assert result["ok"] is False
    assert result["failure_code"] == "BAMBU_3MF_PLATE_GCODE_NOT_FOUND"
    assert result["plate_id"] == 1
    assert not (tmp_path / "patched" / "wrong_plate_only.autoeject.gcode.3mf").exists()


def test_gcode_3mf_patch_adds_missing_plate_md5_sidecar(tmp_path: Path) -> None:
    source = tmp_path / "plate_without_md5.gcode.3mf"
    with zipfile.ZipFile(source, "w") as archive:
        archive.writestr("Metadata/plate_1.gcode", BASE_GCODE)
        archive.writestr("3D/3dmodel.model", "<model />")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center", plate_id=1)

    patched_path = Path(result["patched_artifact_path"])
    assert result["ok"] is True
    with zipfile.ZipFile(patched_path) as archive:
        names = set(archive.namelist())
        patched_gcode = archive.read("Metadata/plate_1.gcode").decode("utf-8")
        patched_md5 = archive.read("Metadata/plate_1.gcode.md5").decode("utf-8").strip()
    assert "Metadata/plate_1.gcode.md5" in names
    assert patched_md5 == hashlib.md5(patched_gcode.encode("utf-8")).hexdigest()


def test_gcode_3mf_patch_writes_manifest_with_hashes_plate_and_validation(tmp_path: Path) -> None:
    source = tmp_path / "plate.gcode.3mf"
    with zipfile.ZipFile(source, "w") as archive:
        archive.writestr("Metadata/plate_1.gcode", BASE_GCODE)
        archive.writestr("3D/3dmodel.model", "<model />")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center", plate_id=1)

    manifest_path = Path(result["manifest_path"])
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert result["ok"] is True
    assert manifest_path.name == "plate.autoeject.gcode.3mf.manifest.json"
    assert manifest["schema"] == "bambu_autoejection_artifact_manifest.v1"
    assert manifest["source_path"] == str(source.resolve())
    assert manifest["patched_artifact_path"] == result["patched_artifact_path"]
    assert manifest["source_sha256"] == result["source_sha256"]
    assert manifest["patched_sha256"] == result["patched_sha256"]
    assert manifest["source_plate_path"] == "Metadata/plate_1.gcode"
    assert result["plate_id"] == 1
    assert manifest["plate_id"] == 1
    assert result["loop_index"] == 1
    assert manifest["loop_index"] == 1
    assert manifest["validation"]["ok"] is True
    assert manifest["will_publish"] is False
    assert manifest["start_enabled"] is False


def test_gcode_3mf_patch_is_idempotent_for_already_autoeject_artifact(tmp_path: Path) -> None:
    source = tmp_path / "plate.gcode.3mf"
    with zipfile.ZipFile(source, "w") as archive:
        archive.writestr("Metadata/plate_1.gcode", BASE_GCODE)
        archive.writestr("3D/3dmodel.model", "<model />")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")
    first = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center", plate_id=1)

    second = patcher.patch_artifact(first["patched_artifact_path"], specimen_id="specimen-cand-1", position="center", plate_id=1)

    patched_path = Path(second["patched_artifact_path"])
    assert second["ok"] is True
    assert patched_path == Path(first["patched_artifact_path"])
    assert patched_path.name == "plate.autoeject.gcode.3mf"
    assert "autoeject.autoeject" not in patched_path.name
    with zipfile.ZipFile(patched_path) as archive:
        patched_gcode = archive.read("Metadata/plate_1.gcode").decode("utf-8")
    assert patched_gcode.count("atr.bambu.autoejection.v1") == 1
    assert Path(second["manifest_path"]).name == "plate.autoeject.gcode.3mf.manifest.json"


def test_bambu_autoejection_validator_blocks_duplicate_marker_and_unexpected_home() -> None:
    validator = BambuGcodeAutoejectionValidator()
    unsafe = """G90
; atr.bambu.autoejection.v1
G28 X Y
; atr.bambu.autoejection.v1
G0 X999 Y999 Z999 F6000
"""

    result = validator.validate(unsafe, source_plate_path="Metadata/plate_1.gcode")

    assert result["ok"] is False
    assert "BAMBU_AUTOEJECTION_TAIL_DUPLICATED" in result["blockers"]
    assert "BAMBU_AUTOEJECTION_UNEXPECTED_HOME" in result["blockers"]
    assert "BAMBU_AUTOEJECTION_UNSAFE_MOTION" in result["blockers"]


def test_bambu_autoejection_validator_blocks_geometry_and_residue_risks() -> None:
    validator = BambuGcodeAutoejectionValidator()
    risky = """; total object count: 2
; object: left-coupon
; FEATURE: Brim
G90
G1 X10 Y10 Z0.2 E0.1
G1 X30 Y30 Z3.0 E0.5
; object: right-coupon
G1 X180 Y180 Z3.0 E0.5
; atr.bambu.autoejection.v1
M400
M190 R40
G0 Z20 F1200
G0 X20 Y245 F6000
G0 X20 Y8 F6000
"""

    result = validator.validate(risky, source_plate_path="Metadata/plate_1.gcode")

    assert result["ok"] is False
    assert "BAMBU_AUTOEJECTION_OBJECT_TOO_LOW" in result["blockers"]
    assert "BAMBU_AUTOEJECTION_MULTI_OBJECT_UNSUPPORTED" in result["blockers"]
    assert "BAMBU_AUTOEJECTION_RESIDUAL_PRIME_OR_SKIRT_RISK" in result["blockers"]
    assert result["object_bounds_mm"]["max_z"] == 3.0


def test_bambu_autoejection_validator_blocks_tall_objects() -> None:
    validator = BambuGcodeAutoejectionValidator()
    too_tall = """G90
G1 X10 Y10 Z0.2 E0.1
G1 X30 Y30 Z210.0 E0.5
; atr.bambu.autoejection.v1
M400
M190 R40
G0 Z220 F1200
"""

    result = validator.validate(too_tall, source_plate_path="Metadata/plate_1.gcode")

    assert result["ok"] is False
    assert "BAMBU_AUTOEJECTION_OBJECT_TOO_TALL" in result["blockers"]


def test_bambu_autoejection_validator_blocks_tail_without_cooldown_wait() -> None:
    validator = BambuGcodeAutoejectionValidator()
    no_cooldown_wait = """G90
G1 X10 Y10 Z0.2 E0.1
G1 X30 Y30 Z10.0 E0.5
; atr.bambu.autoejection.v1
M400
G90
G0 Z20 F1200
G0 X30 Y245 F6000
G0 X30 Y8 F6000
M400
; atr.bambu.autoejection.end
"""

    result = validator.validate(no_cooldown_wait, source_plate_path="Metadata/plate_1.gcode")

    assert result["ok"] is False
    assert "BAMBU_AUTOEJECTION_COOLDOWN_WAIT_MISSING" in result["blockers"]


def test_bambu_autoejection_validator_blocks_tail_before_later_extrusion() -> None:
    validator = BambuGcodeAutoejectionValidator()
    misordered = """G90
M82
G92 E0
G1 X10 Y10 Z0.2 E0.1
G1 X30 Y30 Z10.0 E0.5
; atr.bambu.autoejection.v1
M400
M190 R40
G90
G0 Z20 F3000
G0 X30 Y245 F6000
G0 Z10 F3000
G0 X30 Y8 F6000
M400
; atr.bambu.autoejection.end
G1 X40 Y40 Z12.0 E0.8
M84
"""

    result = validator.validate(misordered, source_plate_path="Metadata/plate_1.gcode")

    assert result["ok"] is False
    assert result["tail_after_last_extrusion"] is False
    assert "BAMBU_AUTOEJECTION_TAIL_BEFORE_LAST_EXTRUSION" in result["blockers"]


def test_post_write_validation_blocks_archive_with_tail_before_later_extrusion(tmp_path: Path) -> None:
    artifact = tmp_path / "misordered.autoeject.gcode.3mf"
    gcode = """G90
M82
G92 E0
G1 X10 Y10 Z10 E0.5
; atr.bambu.autoejection.v1
M190 R40
G0 Z20 F3000
G0 X10 Y245 F6000
G0 Z10 F3000
G0 X10 Y8 F6000
; atr.bambu.autoejection.end
G1 X30 Y30 Z12 E0.8
M84
"""
    with zipfile.ZipFile(artifact, "w") as archive:
        archive.writestr("Metadata/plate_1.gcode", gcode)
        archive.writestr("Metadata/plate_1.gcode.md5", hashlib.md5(gcode.encode("utf-8")).hexdigest())
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher._validate_written_artifact(artifact, source_plate_path="Metadata/plate_1.gcode")

    assert result["ok"] is False
    assert result["reopened"] is True
    assert result["md5_matches"] is True
    assert result["tail_validation"]["tail_after_last_extrusion"] is False


def test_bambu_autoejection_validator_blocks_excessive_xy_ejection_feedrate() -> None:
    validator = BambuGcodeAutoejectionValidator()
    too_fast = """G90
G1 X10 Y10 Z0.2 E0.1
G1 X30 Y30 Z10.0 E0.5
; atr.bambu.autoejection.v1
M400
M190 R40
G90
G0 Z20 F3000
G0 X30 Y245 F15000
G0 X30 Y8 F15000
M400
; atr.bambu.autoejection.end
"""

    result = validator.validate(too_fast, source_plate_path="Metadata/plate_1.gcode")

    assert result["ok"] is False
    assert "BAMBU_AUTOEJECTION_UNSAFE_FEEDRATE" in result["blockers"]


def test_plain_gcode_patch_generates_single_object_top_offset_sweep_tail(tmp_path: Path) -> None:
    source = tmp_path / "specimen.gcode"
    source.write_text(BASE_GCODE, encoding="utf-8")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center")

    patched_text = Path(result["patched_artifact_path"]).read_text(encoding="utf-8")
    assert result["ok"] is True
    assert patched_text.count("atr_sweep_height_fraction=") == 1
    assert "atr_sweep_height_fraction=1.00" in patched_text
    assert "G0 Z10.000 F3000" in patched_text
    assert "G0 Z1.000 F3000" not in patched_text
    assert "G0 Z9.000" not in patched_text


def test_plain_gcode_patch_defaults_to_fifteen_mm_below_object_top_with_ten_mm_floor(tmp_path: Path) -> None:
    source = tmp_path / "tall_specimen.gcode"
    source.write_text(
        "\n".join(
            [
                "G90",
                "G1 X30 Y40 Z0.2 E0.1 F1200",
                "G1 X70 Y80 Z30.0 E0.4 F1200",
                "M84",
            ]
        ),
        encoding="utf-8",
    )
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="tall-specimen", position="center")

    patched_text = Path(result["patched_artifact_path"]).read_text(encoding="utf-8")
    assert result["ok"] is True
    assert result["object_bounds_mm"]["max_z"] == 30.0
    assert "; atr_z_push_offset_mm=15.0" in patched_text
    assert "G0 Z15.000 F3000" in patched_text
    assert "G0 Z20.000 F3000" not in patched_text


@pytest.mark.parametrize(
    ("position", "expected_x"),
    [
        ("left", "G0 X48.000"),
        ("center", "G0 X128.000"),
        ("right", "G0 X208.000"),
    ],
)
def test_standalone_ejection_artifact_generates_position_specific_valid_gcode(
    tmp_path: Path, position: str, expected_x: str
) -> None:
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.build_standalone_ejection_artifact(
        position=position,
        specimen_id=f"eject-{position}-test",
        object_size_mm=[30.0, 30.0, 20.0],
    )

    artifact_path = Path(result["patched_artifact_path"])
    startable_path = Path(result["startable_artifact_path"])
    gcode = artifact_path.read_text(encoding="utf-8")
    assert result["ok"] is True
    assert result["tool"] == "printer.bambu.autoejection_standalone"
    assert artifact_path.name == f"eject-{position}-test.{position}.autoeject.gcode"
    assert startable_path.name == f"eject-{position}-test.{position}.autoeject.gcode.3mf"
    assert result["startable_plate_path"] == "Metadata/plate_1.gcode"
    assert gcode.count("atr.bambu.autoejection.v1") == 1
    assert f"atr_position={position}" in gcode
    assert "M190 R40" in gcode
    assert expected_x in gcode
    assert result["validation"]["ok"] is True
    with zipfile.ZipFile(startable_path) as archive:
        plate_gcode = archive.read("Metadata/plate_1.gcode").decode("utf-8")
        plate_md5 = archive.read("Metadata/plate_1.gcode.md5").decode("utf-8").strip()
    assert "atr.bambu.autoejection.v1" in plate_gcode
    assert f"atr_position={position}" in plate_gcode
    assert plate_md5 == hashlib.md5(plate_gcode.encode("utf-8")).hexdigest()
    assert result["startable_post_write_validation"]["ok"] is True


def test_sweep_test_artifact_generates_full_bed_sweep_without_publish_intent(tmp_path: Path) -> None:
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.build_sweep_test_artifact(specimen_id="sweep-test")

    artifact_path = Path(result["patched_artifact_path"])
    gcode = artifact_path.read_text(encoding="utf-8")
    assert result["ok"] is True
    assert result["tool"] == "printer.bambu.autoejection_sweep_test"
    assert result["status"] == "sweep_test_validated"
    assert result["will_publish"] is False
    assert result["start_enabled"] is False
    assert artifact_path.name == "sweep-test.sweep.autoeject.gcode"
    assert "atr_full_bed_sweep_enabled=true" in gcode
    assert "atr_full_bed_sweep_start" in gcode
    assert "atr_full_bed_sweep_pass=7" in gcode
    assert result["validation"]["ok"] is True
