"""Unit tests for deterministic Bambu G-code autoejection artifact patching."""

from __future__ import annotations

import hashlib
import json
import zipfile
from pathlib import Path

import pytest

from device_bridges.bambu_autoejection import (
    BambuGcodeAutoejectionPatcher,
    BambuGcodeAutoejectionValidator,
)


BASE_GCODE = """; generated by Bambu Studio
; filament start gcode
G90
G1 X10.0 Y20.0 Z0.2 E0.03 F1200
G1 X40.0 Y55.0 Z10.0 E2.50 F1800
M104 S0
M140 S0
M84
"""


def test_plain_gcode_patch_inserts_single_validated_bambu_ejection_tail(tmp_path: Path) -> None:
    source = tmp_path / "specimen.gcode"
    source.write_text(BASE_GCODE, encoding="utf-8")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center")

    patched_path = Path(result["patched_artifact_path"])
    patched_text = patched_path.read_text(encoding="utf-8")
    assert result["ok"] is True
    assert result["source_plate_path"] == "plain_gcode"
    assert patched_path.name == "specimen.autoeject.gcode"
    assert patched_text.count("atr.bambu.autoejection.v1") == 1
    assert "; atr_source_sha256=" in patched_text
    assert "M190 R40" in patched_text
    assert patched_text.index("atr.bambu.autoejection.v1") < patched_text.rindex("M84")
    assert result["validation"]["ok"] is True
    assert result["object_bounds_mm"]["min_x"] == 10.0
    assert result["object_bounds_mm"]["max_y"] == 55.0
    assert result["patched_sha256"] == hashlib.sha256(patched_path.read_bytes()).hexdigest()


def test_plain_gcode_validate_only_does_not_write_patched_artifact(tmp_path: Path) -> None:
    source = tmp_path / "specimen.gcode"
    source.write_text(BASE_GCODE, encoding="utf-8")
    output_dir = tmp_path / "patched"
    patcher = BambuGcodeAutoejectionPatcher(output_dir=output_dir)

    result = patcher.validate_artifact(source, specimen_id="specimen-cand-1", position="center")

    assert result["ok"] is True
    assert result["tool"] == "printer.bambu.autoejection_validate"
    assert result["status"] == "validated"
    assert result["source_plate_path"] == "plain_gcode"
    assert result["validation"]["ok"] is True
    assert result["will_publish"] is False
    assert result["start_enabled"] is False
    assert result["patched_artifact_path"] == ""
    assert result["manifest_path"] == ""
    assert not output_dir.exists()


def test_plain_gcode_patch_records_required_runtime_tail_metadata(tmp_path: Path) -> None:
    source = tmp_path / "specimen.gcode"
    source.write_text(BASE_GCODE, encoding="utf-8")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center")

    patched_text = Path(result["patched_artifact_path"]).read_text(encoding="utf-8")
    assert result["ok"] is True
    assert "; atr_source_plate_path=plain_gcode" in patched_text
    assert "; atr_object_height_mm=10.000" in patched_text
    assert "; atr_material_type=unknown" in patched_text
    assert "; atr_bed_surface=unknown" in patched_text
    assert "; atr_bed_cooldown_c=40" in patched_text
    assert "; atr_cooldown_wait_policy=M190" in patched_text
    assert "; atr_purge_parking_strategy=preserve_slicer_end_gcode_then_eject" in patched_text
    assert "; atr_door_or_front_path_assumption=operator_confirmed_before_publish" in patched_text
    assert "; atr_toolhead_cover_risk_note=operator_confirms_cover_secured_before_publish" in patched_text
    assert "; atr_validation_result=stored_in_manifest" in patched_text
    assert "; atr_patched_artifact_sha256=stored_in_manifest" in patched_text


def test_plain_gcode_patch_is_idempotent_for_already_autoeject_artifact(tmp_path: Path) -> None:
    source = tmp_path / "specimen.gcode"
    source.write_text(BASE_GCODE, encoding="utf-8")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")
    first = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center")

    second = patcher.patch_artifact(first["patched_artifact_path"], specimen_id="specimen-cand-1", position="center")

    patched_path = Path(second["patched_artifact_path"])
    patched_text = patched_path.read_text(encoding="utf-8")
    assert second["ok"] is True
    assert patched_path == Path(first["patched_artifact_path"])
    assert patched_path.name == "specimen.autoeject.gcode"
    assert "autoeject.autoeject" not in patched_path.name
    assert patched_text.count("atr.bambu.autoejection.v1") == 1
    assert Path(second["manifest_path"]).name == "specimen.autoeject.gcode.manifest.json"


def test_plain_gcode_patch_keeps_bambu_end_homing_before_autoejection_tail(tmp_path: Path) -> None:
    source = tmp_path / "bambu_end_sequence.gcode"
    source.write_text(
        """; generated by Bambu Studio
G90
G1 X82.0 Y82.0 Z0.2 E0.03 F1200
G1 X118.0 Y118.0 Z30.0 E2.50 F1800
M106 S0
; FEATURE: Custom
; MACHINE_END_GCODE_START
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
M73 P100 R0
; EXECUTABLE_BLOCK_END
""",
        encoding="utf-8",
    )
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center")

    patched_text = Path(result["patched_artifact_path"]).read_text(encoding="utf-8")
    assert result["ok"] is True
    assert patched_text.index("G28 X0") < patched_text.index("atr.bambu.autoejection.v1")
    assert patched_text.index("atr.bambu.autoejection.end") < patched_text.index("M84")
    assert "BAMBU_AUTOEJECTION_UNEXPECTED_HOME" not in result["validation"]["blockers"]


def test_gcode_3mf_patch_replaces_plate_gcode_and_updates_md5(tmp_path: Path) -> None:
    source = tmp_path / "plate.gcode.3mf"
    original_md5 = hashlib.md5(BASE_GCODE.encode("utf-8")).hexdigest()
    with zipfile.ZipFile(source, "w") as archive:
        archive.writestr("Metadata/plate_1.gcode", BASE_GCODE)
        archive.writestr("Metadata/plate_1.gcode.md5", original_md5)
        archive.writestr("3D/3dmodel.model", "<model />")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="left", plate_id=1)

    patched_path = Path(result["patched_artifact_path"])
    assert result["ok"] is True
    assert patched_path.name == "plate.autoeject.gcode.3mf"
    assert result["source_plate_path"] == "Metadata/plate_1.gcode"
    with zipfile.ZipFile(patched_path) as archive:
        patched_gcode = archive.read("Metadata/plate_1.gcode").decode("utf-8")
        patched_md5 = archive.read("Metadata/plate_1.gcode.md5").decode("utf-8").strip()
        assert archive.read("3D/3dmodel.model").decode("utf-8") == "<model />"
    assert patched_gcode.count("atr.bambu.autoejection.v1") == 1
    assert patched_md5 == hashlib.md5(patched_gcode.encode("utf-8")).hexdigest()
    assert result["validation"]["ok"] is True


def test_gcode_3mf_patch_blocks_missing_requested_plate_instead_of_falling_back(tmp_path: Path) -> None:
    source = tmp_path / "wrong_plate_only.gcode.3mf"
    with zipfile.ZipFile(source, "w") as archive:
        archive.writestr("Metadata/plate_2.gcode", BASE_GCODE)
        archive.writestr("3D/3dmodel.model", "<model />")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center", plate_id=1)

    assert result["ok"] is False
    assert result["failure_code"] == "BAMBU_3MF_PLATE_GCODE_NOT_FOUND"
    assert result["plate_id"] == 1
    assert not (tmp_path / "patched" / "wrong_plate_only.autoeject.gcode.3mf").exists()


def test_gcode_3mf_patch_adds_missing_plate_md5_sidecar(tmp_path: Path) -> None:
    source = tmp_path / "plate_without_md5.gcode.3mf"
    with zipfile.ZipFile(source, "w") as archive:
        archive.writestr("Metadata/plate_1.gcode", BASE_GCODE)
        archive.writestr("3D/3dmodel.model", "<model />")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center", plate_id=1)

    patched_path = Path(result["patched_artifact_path"])
    assert result["ok"] is True
    with zipfile.ZipFile(patched_path) as archive:
        names = set(archive.namelist())
        patched_gcode = archive.read("Metadata/plate_1.gcode").decode("utf-8")
        patched_md5 = archive.read("Metadata/plate_1.gcode.md5").decode("utf-8").strip()
    assert "Metadata/plate_1.gcode.md5" in names
    assert patched_md5 == hashlib.md5(patched_gcode.encode("utf-8")).hexdigest()


def test_gcode_3mf_patch_writes_manifest_with_hashes_plate_and_validation(tmp_path: Path) -> None:
    source = tmp_path / "plate.gcode.3mf"
    with zipfile.ZipFile(source, "w") as archive:
        archive.writestr("Metadata/plate_1.gcode", BASE_GCODE)
        archive.writestr("3D/3dmodel.model", "<model />")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center", plate_id=1)

    manifest_path = Path(result["manifest_path"])
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert result["ok"] is True
    assert manifest_path.name == "plate.autoeject.gcode.3mf.manifest.json"
    assert manifest["schema"] == "bambu_autoejection_artifact_manifest.v1"
    assert manifest["source_path"] == str(source.resolve())
    assert manifest["patched_artifact_path"] == result["patched_artifact_path"]
    assert manifest["source_sha256"] == result["source_sha256"]
    assert manifest["patched_sha256"] == result["patched_sha256"]
    assert manifest["source_plate_path"] == "Metadata/plate_1.gcode"
    assert result["plate_id"] == 1
    assert manifest["plate_id"] == 1
    assert result["loop_index"] == 1
    assert manifest["loop_index"] == 1
    assert manifest["validation"]["ok"] is True
    assert manifest["will_publish"] is False
    assert manifest["start_enabled"] is False


def test_gcode_3mf_patch_is_idempotent_for_already_autoeject_artifact(tmp_path: Path) -> None:
    source = tmp_path / "plate.gcode.3mf"
    with zipfile.ZipFile(source, "w") as archive:
        archive.writestr("Metadata/plate_1.gcode", BASE_GCODE)
        archive.writestr("3D/3dmodel.model", "<model />")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")
    first = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center", plate_id=1)

    second = patcher.patch_artifact(first["patched_artifact_path"], specimen_id="specimen-cand-1", position="center", plate_id=1)

    patched_path = Path(second["patched_artifact_path"])
    assert second["ok"] is True
    assert patched_path == Path(first["patched_artifact_path"])
    assert patched_path.name == "plate.autoeject.gcode.3mf"
    assert "autoeject.autoeject" not in patched_path.name
    with zipfile.ZipFile(patched_path) as archive:
        patched_gcode = archive.read("Metadata/plate_1.gcode").decode("utf-8")
    assert patched_gcode.count("atr.bambu.autoejection.v1") == 1
    assert Path(second["manifest_path"]).name == "plate.autoeject.gcode.3mf.manifest.json"


def test_bambu_autoejection_validator_blocks_duplicate_marker_and_unexpected_home() -> None:
    validator = BambuGcodeAutoejectionValidator()
    unsafe = """G90
; atr.bambu.autoejection.v1
G28 X Y
; atr.bambu.autoejection.v1
G0 X999 Y999 Z999 F6000
"""

    result = validator.validate(unsafe, source_plate_path="Metadata/plate_1.gcode")

    assert result["ok"] is False
    assert "BAMBU_AUTOEJECTION_TAIL_DUPLICATED" in result["blockers"]
    assert "BAMBU_AUTOEJECTION_UNEXPECTED_HOME" in result["blockers"]
    assert "BAMBU_AUTOEJECTION_UNSAFE_MOTION" in result["blockers"]


def test_bambu_autoejection_validator_blocks_geometry_and_residue_risks() -> None:
    validator = BambuGcodeAutoejectionValidator()
    risky = """; total object count: 2
; object: left-coupon
; FEATURE: Brim
G90
G1 X10 Y10 Z0.2 E0.1
G1 X30 Y30 Z3.0 E0.5
; object: right-coupon
G1 X180 Y180 Z3.0 E0.5
; atr.bambu.autoejection.v1
M400
M190 R40
G0 Z20 F1200
G0 X20 Y245 F6000
G0 X20 Y8 F6000
"""

    result = validator.validate(risky, source_plate_path="Metadata/plate_1.gcode")

    assert result["ok"] is False
    assert "BAMBU_AUTOEJECTION_OBJECT_TOO_LOW" in result["blockers"]
    assert "BAMBU_AUTOEJECTION_MULTI_OBJECT_UNSUPPORTED" in result["blockers"]
    assert "BAMBU_AUTOEJECTION_RESIDUAL_PRIME_OR_SKIRT_RISK" in result["blockers"]
    assert result["object_bounds_mm"]["max_z"] == 3.0


def test_bambu_autoejection_validator_blocks_tall_objects() -> None:
    validator = BambuGcodeAutoejectionValidator()
    too_tall = """G90
G1 X10 Y10 Z0.2 E0.1
G1 X30 Y30 Z210.0 E0.5
; atr.bambu.autoejection.v1
M400
M190 R40
G0 Z220 F1200
"""

    result = validator.validate(too_tall, source_plate_path="Metadata/plate_1.gcode")

    assert result["ok"] is False
    assert "BAMBU_AUTOEJECTION_OBJECT_TOO_TALL" in result["blockers"]


def test_bambu_autoejection_validator_blocks_tail_without_cooldown_wait() -> None:
    validator = BambuGcodeAutoejectionValidator()
    no_cooldown_wait = """G90
G1 X10 Y10 Z0.2 E0.1
G1 X30 Y30 Z10.0 E0.5
; atr.bambu.autoejection.v1
M400
G90
G0 Z20 F1200
G0 X30 Y245 F6000
G0 X30 Y8 F6000
M400
; atr.bambu.autoejection.end
"""

    result = validator.validate(no_cooldown_wait, source_plate_path="Metadata/plate_1.gcode")

    assert result["ok"] is False
    assert "BAMBU_AUTOEJECTION_COOLDOWN_WAIT_MISSING" in result["blockers"]


def test_bambu_autoejection_validator_blocks_excessive_xy_ejection_feedrate() -> None:
    validator = BambuGcodeAutoejectionValidator()
    too_fast = """G90
G1 X10 Y10 Z0.2 E0.1
G1 X30 Y30 Z10.0 E0.5
; atr.bambu.autoejection.v1
M400
M190 R40
G90
G0 Z20 F1200
G0 X30 Y245 F5000
G0 X30 Y8 F5000
M400
; atr.bambu.autoejection.end
"""

    result = validator.validate(too_fast, source_plate_path="Metadata/plate_1.gcode")

    assert result["ok"] is False
    assert "BAMBU_AUTOEJECTION_UNSAFE_FEEDRATE" in result["blockers"]


def test_plain_gcode_patch_generates_object_height_multi_sweep_tail(tmp_path: Path) -> None:
    source = tmp_path / "specimen.gcode"
    source.write_text(BASE_GCODE, encoding="utf-8")
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.patch_artifact(source, specimen_id="specimen-cand-1", position="center")

    patched_text = Path(result["patched_artifact_path"]).read_text(encoding="utf-8")
    assert result["ok"] is True
    assert patched_text.count("atr_sweep_height_fraction=") >= 3
    assert "G0 Z9.000" in patched_text
    assert "G0 Z6.000" in patched_text
    assert "G0 Z4.000" in patched_text


@pytest.mark.parametrize(
    ("position", "expected_x"),
    [
        ("left", "G0 X48.000"),
        ("center", "G0 X128.000"),
        ("right", "G0 X208.000"),
    ],
)
def test_standalone_ejection_artifact_generates_position_specific_valid_gcode(
    tmp_path: Path, position: str, expected_x: str
) -> None:
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.build_standalone_ejection_artifact(
        position=position,
        specimen_id=f"eject-{position}-test",
        object_size_mm=[30.0, 30.0, 20.0],
    )

    artifact_path = Path(result["patched_artifact_path"])
    startable_path = Path(result["startable_artifact_path"])
    gcode = artifact_path.read_text(encoding="utf-8")
    assert result["ok"] is True
    assert result["tool"] == "printer.bambu.autoejection_standalone"
    assert artifact_path.name == f"eject-{position}-test.{position}.autoeject.gcode"
    assert startable_path.name == f"eject-{position}-test.{position}.autoeject.gcode.3mf"
    assert result["startable_plate_path"] == "Metadata/plate_1.gcode"
    assert gcode.count("atr.bambu.autoejection.v1") == 1
    assert f"atr_position={position}" in gcode
    assert "M190 R40" in gcode
    assert expected_x in gcode
    assert result["validation"]["ok"] is True
    with zipfile.ZipFile(startable_path) as archive:
        plate_gcode = archive.read("Metadata/plate_1.gcode").decode("utf-8")
    assert "atr.bambu.autoejection.v1" in plate_gcode
    assert f"atr_position={position}" in plate_gcode


def test_sweep_test_artifact_generates_full_bed_sweep_without_publish_intent(tmp_path: Path) -> None:
    patcher = BambuGcodeAutoejectionPatcher(output_dir=tmp_path / "patched")

    result = patcher.build_sweep_test_artifact(specimen_id="sweep-test")

    artifact_path = Path(result["patched_artifact_path"])
    gcode = artifact_path.read_text(encoding="utf-8")
    assert result["ok"] is True
    assert result["tool"] == "printer.bambu.autoejection_sweep_test"
    assert result["status"] == "sweep_test_validated"
    assert result["will_publish"] is False
    assert result["start_enabled"] is False
    assert artifact_path.name == "sweep-test.sweep.autoeject.gcode"
    assert "atr_full_bed_sweep_enabled=true" in gcode
    assert "atr_full_bed_sweep_start" in gcode
    assert "atr_full_bed_sweep_pass=7" in gcode
    assert result["validation"]["ok"] is True
